### PR TITLE
fix black borders on android

### PR DESCRIPTION
**Pull request by ghost**
Hope it helps ;)

Screenshot_1563750942
Simulator Screen Shot - iPhone 5s - 2019-07-22 at 00 15 44

### CODE REVIEW

**Comment by saurabhgour** [comment]
Hi millenagm, sorry I didn't check this, is the fix in the PR still working?

**Comment by vankraster** [comment]
I have used you'r component but it's not working, the progress it's not showing well. Te round progress bar does not overlaps the background one, it seems a bug in renderThirdLayer . because it is traslated on X axe

**Comment by ghost** [comment]
@saurabhgour, not sure. It's been a while since I've fixed that :(

**Comment by TheRakeshPurohit** [comment]
merge it

**Review by TheRakeshPurohit — APPROVED** [review]

**Comment by saurabhgour** [comment]
Merged

**Pull request merged**
